/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: songti24.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character disabled:  0x31 (49)                                     *
* Character enabled:   0x32 (50)                                     *
* Character enabled:   0x31 (49)                                     *
* Character enabled:   0x33 (51)                                     *
* Character enabled:   0x34 (52)                                     *
* Character enabled:   0x35 (53)                                     *
* Character enabled:   0x36 (54)                                     *
* Character enabled:   0x37 (55)                                     *
* Character enabled:   0x39 (57)                                     *
* Character enabled:   0x38 (56)                                     *
* Character enabled:   0x2D (45)                                     *
* Character enabled:   0x2E (46)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti24;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_002D[ 48] = { /* code 002D, HYPHEN-MINUS */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_002E[ 48] = { /* code 002E, FULL STOP */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_0030[ 48] = { /* code 0030, DIGIT ZERO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,________,
  ___XX__X,X_______,
  __XX____,XX______,
  __XX____,XX______,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  __XX____,XX______,
  __XX____,XX______,
  ___XX__X,X_______,
  ____XXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_0031[ 48] = { /* code 0031, DIGIT ONE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  _____XX_,________,
  __XXXXX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  __XXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_0032[ 48] = { /* code 0032, DIGIT TWO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __X____X,X_______,
  _X______,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  ________,XX______,
  _______X,X_______,
  _______X,X_______,
  ______XX,________,
  _____X__,________,
  ____X___,________,
  ___X____,_X______,
  __X_____,_X______,
  _X______,_X______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_0033[ 48] = { /* code 0033, DIGIT THREE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __X___XX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _______X,X_______,
  ______XX,________,
  ____XXX_,________,
  _______X,X_______,
  ________,X_______,
  ________,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  __X____X,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_0034[ 48] = { /* code 0034, DIGIT FOUR */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,X_______,
  _______X,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _____X_X,X_______,
  ____X__X,X_______,
  ____X__X,X_______,
  ___X___X,X_______,
  __X____X,X_______,
  __X____X,X_______,
  _X_____X,X_______,
  _XXXXXXX,XXX_____,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _____XXX,XXX_____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_0035[ 48] = { /* code 0035, DIGIT FIVE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  __X_____,________,
  __X_____,________,
  __X_____,________,
  __X_____,________,
  __X_XXXX,________,
  __XX___X,X_______,
  __X_____,XX______,
  ________,XX______,
  ________,XX______,
  _XX_____,XX______,
  _XX_____,XX______,
  _X_____X,X_______,
  __X____X,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_0036[ 48] = { /* code 0036, DIGIT SIX */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XXX,X_______,
  ___XX___,XX______,
  __XX____,XX______,
  __XX____,________,
  __X_____,________,
  _XX_____,________,
  _XX__XXX,X_______,
  _XX_X___,XX______,
  _XXX____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  __X_____,_XX_____,
  __XX____,_X______,
  ___XX___,XX______,
  ____XXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_0037[ 48] = { /* code 0037, DIGIT SEVEN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,XXX_____,
  __XXXXXX,XXX_____,
  __XX____,_X______,
  __X_____,X_______,
  __X_____,X_______,
  ________,X_______,
  _______X,________,
  _______X,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_0038[ 48] = { /* code 0038, DIGIT EIGHT */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,X_______,
  __XX____,XX______,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XXX____,_X______,
  __XXXX__,XX______,
  ____XXXX,________,
  __XX__XX,X_______,
  __X_____,XX______,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  __XX____,XX______,
  ____XXXX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti24_0039[ 48] = { /* code 0039, DIGIT NINE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,________,
  __XX____,X_______,
  __XX____,XX______,
  _XX_____,_X______,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  _XX_____,XXX_____,
  __XX___X,_XX_____,
  ___XXXX_,_XX_____,
  ________,_XX_____,
  ________,XX______,
  ________,XX______,
  __XX____,X_______,
  __XX___X,X_______,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsongti24_CharInfo[12] = {
   {  12,  12,  2, acGUI_Fontsongti24_002D } /* code 002D */
  ,{  12,  12,  2, acGUI_Fontsongti24_002E } /* code 002E */
  ,{  12,  12,  2, acGUI_Fontsongti24_0030 } /* code 0030 */
  ,{  12,  12,  2, acGUI_Fontsongti24_0031 } /* code 0031 */
  ,{  12,  12,  2, acGUI_Fontsongti24_0032 } /* code 0032 */
  ,{  12,  12,  2, acGUI_Fontsongti24_0033 } /* code 0033 */
  ,{  12,  12,  2, acGUI_Fontsongti24_0034 } /* code 0034 */
  ,{  12,  12,  2, acGUI_Fontsongti24_0035 } /* code 0035 */
  ,{  12,  12,  2, acGUI_Fontsongti24_0036 } /* code 0036 */
  ,{  12,  12,  2, acGUI_Fontsongti24_0037 } /* code 0037 */
  ,{  12,  12,  2, acGUI_Fontsongti24_0038 } /* code 0038 */
  ,{  12,  12,  2, acGUI_Fontsongti24_0039 } /* code 0039 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti24_Prop2 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_Fontsongti24_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti24_Prop1 = {
   0x002D /* first character */
  ,0x002E /* last character  */
  ,&GUI_Fontsongti24_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsongti24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsongti24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

