/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: song48.c                                              *
* Font:        Consolas                                              *
* Height:      48                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  48                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x3C (60)                                     *
* Character enabled:   0x3E (62)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong48;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsong48_003C[144] = { /* code 003C, LESS-THAN SIGN */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,_X______,
  ________,________,XXX_____,
  ________,______XX,XXXX____,
  ________,_____XXX,XXXXX___,
  ________,____XXXX,XXX_____,
  ________,__XXXXXX,XX______,
  ________,_XXXXXXX,X_______,
  _______X,XXXXXXX_,________,
  ______XX,XXXXXX__,________,
  _____XXX,XXXX____,________,
  ___XXXXX,XXX_____,________,
  __XXXXXX,X_______,________,
  ___XXXXX,XX______,________,
  ____XXXX,XXX_____,________,
  _____XXX,XXXX____,________,
  ______XX,XXXXX___,________,
  _______X,XXXXXX__,________,
  ________,XXXXXXX_,________,
  ________,_XXXXXXX,________,
  ________,__XXXXXX,________,
  ________,___XXXXX,________,
  ________,____XXX_,________,
  ________,_____X__,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong48_003E[144] = { /* code 003E, GREATER-THAN SIGN */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_X______,________,
  ________,XXX_____,________,
  _______X,XXXX____,________,
  ______XX,XXXXX___,________,
  _______X,XXXXXX__,________,
  ________,XXXXXXX_,________,
  ________,_XXXXXXX,________,
  ________,__XXXXXX,X_______,
  ________,___XXXXX,XX______,
  ________,____XXXX,XXX_____,
  ________,_____XXX,XXXX____,
  ________,______XX,XXXXX___,
  ________,____XXXX,XXXX____,
  ________,___XXXXX,XX______,
  ________,_XXXXXXX,X_______,
  ________,XXXXXXXX,________,
  ______XX,XXXXXX__,________,
  _____XXX,XXXXX___,________,
  ____XXXX,XXX_____,________,
  __XXXXXX,XX______,________,
  ___XXXXX,X_______,________,
  ____XXX_,________,________,
  _____X__,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsong48_CharInfo[2] = {
   {  23,  23,  3, acGUI_Fontsong48_003C } /* code 003C */
  ,{  23,  23,  3, acGUI_Fontsong48_003E } /* code 003E */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong48_Prop2 = {
   0x003E /* first character */
  ,0x003E /* last character  */
  ,&GUI_Fontsong48_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong48_Prop1 = {
   0x003C /* first character */
  ,0x003C /* last character  */
  ,&GUI_Fontsong48_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsong48_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsong48 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,48 /* height of font  */
  ,48 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsong48_Prop1}
  ,38 /* Baseline */
  ,20 /* Height of lowercase characters */
  ,26 /* Height of capital characters */
};

